//roboto font use it in layout.tsx
import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import "./globals.css";
import NavigationBar from "./component/NavigationBar";
import { ThemeProvider } from "@/components/ui/theme-provider";
import CustomFooter from "./component/Footer";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={roboto.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavigationBar />
            {children}
            <CustomFooter />
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
